version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cables_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Microsoft1!
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"